package survey;
import nng.nng_socket_s;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Ptr;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>survey</b><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("survey") 
@Runtime(CRuntime.class) 
public class SurveyLibrary {
	static {
		BridJ.register();
	}
	/** <i>native declaration : protocol/survey0/survey.h</i> */
	public static final String NNG_OPT_SURVEYOR_SURVEYTIME = (String)"surveyor:survey-time";
	/**
	 * Original signature : <code>int nng_surveyor0_open(nng_socket*)</code><br>
	 * <i>native declaration : protocol/survey0/survey.h:2</i>
	 */
	@Name("nng_surveyor0_open") 
	public static int nngSurveyor0Open(Pointer<nng_socket_s > nng_socketPtr1) {
		return nngSurveyor0Open(Pointer.getPeer(nng_socketPtr1));
	}
	@Name("nng_surveyor0_open") 
	protected native static int nngSurveyor0Open(@Ptr long nng_socketPtr1);
	/**
	 * Original signature : <code>int nng_surveyor0_open_raw(nng_socket*)</code><br>
	 * <i>native declaration : protocol/survey0/survey.h:4</i>
	 */
	@Name("nng_surveyor0_open_raw") 
	public static int nngSurveyor0OpenRaw(Pointer<nng_socket_s > nng_socketPtr1) {
		return nngSurveyor0OpenRaw(Pointer.getPeer(nng_socketPtr1));
	}
	@Name("nng_surveyor0_open_raw") 
	protected native static int nngSurveyor0OpenRaw(@Ptr long nng_socketPtr1);
}
