package nng.ipc;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>ipc</b><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ipc") 
@Runtime(CRuntime.class) 
public class IpcLibrary {
	static {
		BridJ.register();
	}
	/** <i>native declaration : transport/ipc/ipc.h</i> */
	public static final String NNG_OPT_IPC_SECURITY_DESCRIPTOR = (String)"ipc:security-descriptor";
	/** <i>native declaration : transport/ipc/ipc.h</i> */
	public static final String NNG_OPT_IPC_PERMISSIONS = (String)"ipc:permissions";
	/** <i>native declaration : transport/ipc/ipc.h</i> */
	public static final String NNG_OPT_IPC_PEER_UID = (String)"ipc:peer-uid";
	/** <i>native declaration : transport/ipc/ipc.h</i> */
	public static final String NNG_OPT_IPC_PEER_GID = (String)"ipc:peer-gid";
	/** <i>native declaration : transport/ipc/ipc.h</i> */
	public static final String NNG_OPT_IPC_PEER_PID = (String)"ipc:peer-pid";
	/** <i>native declaration : transport/ipc/ipc.h</i> */
	public static final String NNG_OPT_IPC_PEER_ZONEID = (String)"ipc:peer-zoneid";
	/**
	 * the same host computer.<br>
	 * Original signature : <code>int nng_ipc_register()</code><br>
	 * <i>native declaration : transport/ipc/ipc.h:4</i>
	 */
	@Name("nng_ipc_register") 
	public static native int nngIpcRegister();
}
