/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.7/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    `eclipse`
}

dependencies {
    // https://mvnrepository.com/artifact/net.java.dev.jna/jna
    compileOnly("net.java.dev.jna:jna:4.5.2")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

// In this section you declare where to find the dependencies of your project
repositories {
    jcenter()
    mavenCentral()
}
