package nng;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : nng.h:662</i><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nng") 
public class nng_url extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * never NULL<br>
	 * C type : char*
	 */
	@Field(0) 
	public Pointer<Byte > u_rawurl() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * never NULL<br>
	 * C type : char*
	 */
	@Field(0) 
	public nng_url u_rawurl(Pointer<Byte > u_rawurl) {
		this.io.setPointerField(this, 0, u_rawurl);
		return this;
	}
	/**
	 * never NULL<br>
	 * C type : char*
	 */
	@Field(1) 
	public Pointer<Byte > u_scheme() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * never NULL<br>
	 * C type : char*
	 */
	@Field(1) 
	public nng_url u_scheme(Pointer<Byte > u_scheme) {
		this.io.setPointerField(this, 1, u_scheme);
		return this;
	}
	/**
	 * will be NULL if not specified<br>
	 * C type : char*
	 */
	@Field(2) 
	public Pointer<Byte > u_userinfo() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * will be NULL if not specified<br>
	 * C type : char*
	 */
	@Field(2) 
	public nng_url u_userinfo(Pointer<Byte > u_userinfo) {
		this.io.setPointerField(this, 2, u_userinfo);
		return this;
	}
	/**
	 * including colon and port<br>
	 * C type : char*
	 */
	@Field(3) 
	public Pointer<Byte > u_host() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * including colon and port<br>
	 * C type : char*
	 */
	@Field(3) 
	public nng_url u_host(Pointer<Byte > u_host) {
		this.io.setPointerField(this, 3, u_host);
		return this;
	}
	/**
	 * name only, will be "" if not specified<br>
	 * C type : char*
	 */
	@Field(4) 
	public Pointer<Byte > u_hostname() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * name only, will be "" if not specified<br>
	 * C type : char*
	 */
	@Field(4) 
	public nng_url u_hostname(Pointer<Byte > u_hostname) {
		this.io.setPointerField(this, 4, u_hostname);
		return this;
	}
	/**
	 * port, will be "" if not specified<br>
	 * C type : char*
	 */
	@Field(5) 
	public Pointer<Byte > u_port() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * port, will be "" if not specified<br>
	 * C type : char*
	 */
	@Field(5) 
	public nng_url u_port(Pointer<Byte > u_port) {
		this.io.setPointerField(this, 5, u_port);
		return this;
	}
	/**
	 * path, will be "" if not specified<br>
	 * C type : char*
	 */
	@Field(6) 
	public Pointer<Byte > u_path() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * path, will be "" if not specified<br>
	 * C type : char*
	 */
	@Field(6) 
	public nng_url u_path(Pointer<Byte > u_path) {
		this.io.setPointerField(this, 6, u_path);
		return this;
	}
	/**
	 * without '?', will be NULL if not specified<br>
	 * C type : char*
	 */
	@Field(7) 
	public Pointer<Byte > u_query() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * without '?', will be NULL if not specified<br>
	 * C type : char*
	 */
	@Field(7) 
	public nng_url u_query(Pointer<Byte > u_query) {
		this.io.setPointerField(this, 7, u_query);
		return this;
	}
	/**
	 * without '#', will be NULL if not specified<br>
	 * C type : char*
	 */
	@Field(8) 
	public Pointer<Byte > u_fragment() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * without '#', will be NULL if not specified<br>
	 * C type : char*
	 */
	@Field(8) 
	public nng_url u_fragment(Pointer<Byte > u_fragment) {
		this.io.setPointerField(this, 8, u_fragment);
		return this;
	}
	/**
	 * includes query and fragment, "" if not specified<br>
	 * C type : char*
	 */
	@Field(9) 
	public Pointer<Byte > u_requri() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * includes query and fragment, "" if not specified<br>
	 * C type : char*
	 */
	@Field(9) 
	public nng_url u_requri(Pointer<Byte > u_requri) {
		this.io.setPointerField(this, 9, u_requri);
		return this;
	}
	public nng_url() {
		super();
	}
	public nng_url(Pointer pointer) {
		super(pointer);
	}
}
