package nng.websocket;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>websocket</b><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("websocket") 
@Runtime(CRuntime.class) 
public class WebsocketLibrary {
	static {
		BridJ.register();
	}
	/** <i>native declaration : transport/ws/websocket.h</i> */
	public static final String NNG_OPT_WS_REQUEST_HEADERS = (String)"ws:request-headers";
	/** <i>native declaration : transport/ws/websocket.h</i> */
	public static final String NNG_OPT_WS_RESPONSE_HEADERS = (String)"ws:response-headers";
	/** <i>native declaration : transport/ws/websocket.h</i> */
	public static final String NNG_OPT_WSS_REQUEST_HEADERS = (String)"ws:request-headers";
	/** <i>native declaration : transport/ws/websocket.h</i> */
	public static final String NNG_OPT_WSS_RESPONSE_HEADERS = (String)"ws:response-headers";
	/**
	 * WebSocket transport.  This is used for communication via WebSocket.<br>
	 * Original signature : <code>int nng_ws_register()</code><br>
	 * <i>native declaration : transport/ws/websocket.h:4</i>
	 */
	@Name("nng_ws_register") 
	public static native int nngWsRegister();
	/**
	 * These aliases are for WSS naming consistency.<br>
	 * Original signature : <code>int nng_wss_register()</code><br>
	 * <i>native declaration : transport/ws/websocket.h:9</i>
	 */
	@Name("nng_wss_register") 
	public static native int nngWssRegister();
}
