package nng.inproc;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>inproc</b><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("inproc") 
@Runtime(CRuntime.class) 
public class InprocLibrary {
	static {
		BridJ.register();
	}
	/**
	 * inproc transport.  This is used for intra-process communication.<br>
	 * Original signature : <code>int nng_inproc_register()</code><br>
	 * <i>native declaration : transport/inproc/inproc.h:4</i>
	 */
	@Name("nng_inproc_register") 
	public static native int nngInprocRegister();
}
