package nng.nng;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : nng.h:30</i><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nng") 
public class nng_sockaddr_path extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short sa_family() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public nng_sockaddr_path sa_family(short sa_family) {
		this.io.setShortField(this, 0, sa_family);
		return this;
	}
	/** C type : char[(128)] */
	@Array({128}) 
	@Field(1) 
	public Pointer<Byte > sa_path() {
		return this.io.getPointerField(this, 1);
	}
	public nng_sockaddr_path() {
		super();
	}
	public nng_sockaddr_path(Pointer pointer) {
		super(pointer);
	}
}
