package nng.nng;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : nng.h:51</i><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nng") 
public class nng_sockaddr_zt extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short sa_family() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public nng_sockaddr_zt sa_family(short sa_family) {
		this.io.setShortField(this, 0, sa_family);
		return this;
	}
	@Field(1) 
	public long sa_nwid() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public nng_sockaddr_zt sa_nwid(long sa_nwid) {
		this.io.setLongField(this, 1, sa_nwid);
		return this;
	}
	@Field(2) 
	public long sa_nodeid() {
		return this.io.getLongField(this, 2);
	}
	@Field(2) 
	public nng_sockaddr_zt sa_nodeid(long sa_nodeid) {
		this.io.setLongField(this, 2, sa_nodeid);
		return this;
	}
	@Field(3) 
	public int sa_port() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public nng_sockaddr_zt sa_port(int sa_port) {
		this.io.setIntField(this, 3, sa_port);
		return this;
	}
	public nng_sockaddr_zt() {
		super();
	}
	public nng_sockaddr_zt(Pointer pointer) {
		super(pointer);
	}
}
