package nng.nng;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : nng.h:63</i><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("nng") 
public class nng_sockaddr extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short s_family() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public nng_sockaddr s_family(short s_family) {
		this.io.setShortField(this, 0, s_family);
		return this;
	}
	/** C type : nng_sockaddr_ipc */
	@Field(1) 
	public nng_sockaddr_path s_ipc() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : nng_sockaddr_ipc */
	@Field(1) 
	public nng_sockaddr s_ipc(nng_sockaddr_path s_ipc) {
		this.io.setNativeObjectField(this, 1, s_ipc);
		return this;
	}
	/** C type : nng_sockaddr_inproc */
	@Field(2) 
	public nng_sockaddr_inproc s_inproc() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : nng_sockaddr_inproc */
	@Field(2) 
	public nng_sockaddr s_inproc(nng_sockaddr_inproc s_inproc) {
		this.io.setNativeObjectField(this, 2, s_inproc);
		return this;
	}
	/** C type : nng_sockaddr_in6 */
	@Field(3) 
	public nng_sockaddr_in6 s_in6() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : nng_sockaddr_in6 */
	@Field(3) 
	public nng_sockaddr s_in6(nng_sockaddr_in6 s_in6) {
		this.io.setNativeObjectField(this, 3, s_in6);
		return this;
	}
	/** C type : nng_sockaddr_in */
	@Field(4) 
	public nng_sockaddr_in s_in() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : nng_sockaddr_in */
	@Field(4) 
	public nng_sockaddr s_in(nng_sockaddr_in s_in) {
		this.io.setNativeObjectField(this, 4, s_in);
		return this;
	}
	/** C type : nng_sockaddr_zt */
	@Field(5) 
	public nng_sockaddr_zt s_zt() {
		return this.io.getNativeObjectField(this, 5);
	}
	/** C type : nng_sockaddr_zt */
	@Field(5) 
	public nng_sockaddr s_zt(nng_sockaddr_zt s_zt) {
		this.io.setNativeObjectField(this, 5, s_zt);
		return this;
	}
	public nng_sockaddr() {
		super();
	}
	public nng_sockaddr(Pointer pointer) {
		super(pointer);
	}
}
