package nng.zerotier;
import java.util.Collections;
import java.util.Iterator;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.FlagSet;
import org.bridj.IntValuedEnum;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>zerotier</b><br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="https://github.com/nativelibs4java">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("zerotier") 
@Runtime(CRuntime.class) 
public class ZerotierLibrary {
	static {
		BridJ.register();
	}
	/**
	 * underlying ZeroTier transport changes.<br>
	 * enum values<br>
	 * <i>native declaration : transport/zerotier/zerotier.h:9</i>
	 */
	public enum nng_zt_status implements IntValuedEnum<nng_zt_status > {
		NNG_ZT_STATUS_UP(0),
		NNG_ZT_STATUS_CONFIG(1),
		NNG_ZT_STATUS_DENIED(2),
		NNG_ZT_STATUS_NOTFOUND(3),
		NNG_ZT_STATUS_ERROR(4),
		NNG_ZT_STATUS_OBSOLETE(5),
		NNG_ZT_STATUS_UNKNOWN(6);
		nng_zt_status(long value) {
			this.value = value;
		}
		public final long value;
		public long value() {
			return this.value;
		}
		public Iterator<nng_zt_status > iterator() {
			return Collections.singleton(this).iterator();
		}
		public static IntValuedEnum<nng_zt_status > fromValue(int value) {
			return FlagSet.fromValue(value, values());
		}
	};
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_HOME = (String)"zt:home";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_NWID = (String)"zt:nwid";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_NODE = (String)"zt:node";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_NETWORK_STATUS = (String)"zt:network-status";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_NETWORK_NAME = (String)"zt:network-name";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_PING_TIME = (String)"zt:ping-time";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_PING_TRIES = (String)"zt:ping-tries";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_CONN_TIME = (String)"zt:conn-time";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_CONN_TRIES = (String)"zt:conn-tries";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_MTU = (String)"zt:mtu";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_ORBIT = (String)"zt:orbit";
	/** <i>native declaration : transport/zerotier/zerotier.h</i> */
	public static final String NNG_OPT_ZT_DEORBIT = (String)"zt:deorbit";
	/**
	 * Original signature : <code>int nng_zt_register()</code><br>
	 * <i>native declaration : transport/zerotier/zerotier.h:11</i>
	 */
	@Name("nng_zt_register") 
	public static native int nngZtRegister();
}
